include_recipe "command_recipe.rb"
include_recipe "nginx_recipe.rb"
include_recipe "php_recipe.rb"
include_recipe "mysql_recipe.rb"
include_recipe "phpmyadmin_recipe.rb"
include_recipe "package_recipe.rb"
include_recipe "service_recipe.rb"
